# Generated by Django 3.2.8 on 2021-11-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
    ]
