# Generated by Django 3.2.8 on 2021-12-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity', models.CharField(choices=[('PLAYDATE', 'playdate'), ('WATER_TRAINING', 'train-water'), ('AGILITY_TRAINING', 'train-agility'), ('HIKE', 'hike')], max_length=100)),
                ('time_block', models.CharField(choices=[('PLAYDATE_MORNING', '09:00 - 11:00'), ('PLAYDATE_AFTERNOON', '13:00 - 15:00'), ('TRAINING', '08:00 - 10:00'), ('HIKE', '13:00 - 16:00')], max_length=30)),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('name_of_buddy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.dog')),
            ],
        ),
    ]
