# Generated by Django 3.2.8 on 2021-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='buddy_name',
        ),
        migrations.AddField(
            model_name='event',
            name='buddy_name',
            field=models.ManyToManyField(blank=True, to='dogs.Dog'),
        ),
    ]
