# Generated by Django 3.2.8 on 2021-11-25 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_name', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('resided_since', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dogs/')),
                ('story', models.TextField(blank=True, max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.breed')),
                ('job', models.ManyToManyField(blank=True, to='dogs.Job')),
            ],
        ),
    ]
