# Generated by Django 3.2.8 on 2021-11-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['resided_since']},
        ),
    ]
